#!/usr/bin/env node
/**
 * Reads .txt prompt files from src/prompts/ and generates src/prompts/index.js.
 * Run automatically via the "prebuild" npm script.
 *
 * Edit prompts by modifying the .txt files, then rebuild.
 */
const fs = require('fs');
const path = require('path');

const PROMPTS_DIR = path.join(__dirname, '..', 'src', 'prompts');

function readPrompt(filename) {
  return fs.readFileSync(path.join(PROMPTS_DIR, filename), 'utf-8');
}

const getWord = readPrompt('get-word.txt');
const checkSense = readPrompt('check-sense.txt');
const synonym = readPrompt('synonym.txt');
const retriesRaw = readPrompt('retries.txt');
const retries = retriesRaw.split('\n').filter((l) => l.trim());

const output = `// AUTO-GENERATED by scripts/sync-prompts.js — do not edit directly.
// Edit the .txt files in src/prompts/ and rebuild.

/* eslint-disable no-template-curly-in-string */

export const getWordPrompt = ${JSON.stringify(getWord)};

export const checkSensePrompt = ${JSON.stringify(checkSense)};

export const synonymPrompt = ${JSON.stringify(synonym)};

export const retryTemplates = ${JSON.stringify(retries, null, 2)};
`;

fs.writeFileSync(path.join(PROMPTS_DIR, 'index.js'), output, 'utf-8');
console.log('[sync-prompts] Generated src/prompts/index.js from .txt files');
