// AUTO-GENERATED by scripts/sync-prompts.js — do not edit directly.
// Edit the .txt files in src/prompts/ and rebuild.

/* eslint-disable no-template-curly-in-string */

export const getWordPrompt = "Extract keywords from the description below. Output ONLY a comma-separated list of nouns and colors. Nothing else.\n\nDescription: ${caption}\n\nKeywords:";

export const checkSensePrompt = "The image shows: \"${caption}\". Does the word \"${word}\" relate to this image? Answer yes or no:";

export const synonymPrompt = "Image description: \"${caption}\"\nPick a word related to this image and give a synonym (3 to 7 letters).\nSynonym:";

export const retryTemplates = [
  "\"${caption}\" - one word (3 to 7 letters) that captures the mood:",
  "Objects in scene: ${caption}\\nWord (3-7 letters):",
  "The photo shows ${caption}. Name one thing in 3 to 7 letters:",
  "Describe \"${caption}\" in one word (3-7 letters):",
  "${caption}\\nWord:"
];
